using System;
using System.Collections;

namespace System.Data.Odbc
{
	/// <summary>Collects all errors generated by the <see cref="T:System.Data.Odbc.OdbcDataAdapter" />. This class cannot be inherited.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x02000123 RID: 291
	[Serializable]
	public sealed class OdbcErrorCollection : IEnumerable, ICollection
	{
		// Token: 0x0600106F RID: 4207 RVA: 0x00040C10 File Offset: 0x0003EE10
		internal OdbcErrorCollection()
		{
		}

		/// <summary>For a description of this member, see <see cref="M:System.Collections.ICollection.SyncRoot" />.</summary>
		// Token: 0x170002C3 RID: 707
		// (get) Token: 0x06001070 RID: 4208 RVA: 0x00040C24 File Offset: 0x0003EE24
		object ICollection.SyncRoot
		{
			get
			{
				return this._items.SyncRoot;
			}
		}

		/// <summary>For a description of this member, see <see cref="M:System.Collections.ICollection.IsSynchronized" />.</summary>
		// Token: 0x170002C4 RID: 708
		// (get) Token: 0x06001071 RID: 4209 RVA: 0x00040C34 File Offset: 0x0003EE34
		bool ICollection.IsSynchronized
		{
			get
			{
				return this._items.IsSynchronized;
			}
		}

		/// <summary>Gets the number of errors in the collection.</summary>
		/// <returns>The total number of errors in the collection.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170002C5 RID: 709
		// (get) Token: 0x06001072 RID: 4210 RVA: 0x00040C44 File Offset: 0x0003EE44
		public int Count
		{
			get
			{
				return this._items.Count;
			}
		}

		/// <summary>Gets the error at the specified index.</summary>
		/// <returns>An <see cref="T:System.Data.Odbc.OdbcError" /> that contains the error at the specified index. </returns>
		/// <param name="i">The zero-based index of the error to retrieve. </param>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170002C6 RID: 710
		public OdbcError this[int i]
		{
			get
			{
				return (OdbcError)this._items[i];
			}
		}

		// Token: 0x06001074 RID: 4212 RVA: 0x00040C68 File Offset: 0x0003EE68
		internal void Add(OdbcError error)
		{
			this._items.Add(error);
		}

		/// <summary>Copies the elements of the <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> into an array, starting at the specified index within the array.</summary>
		/// <param name="array">The array into which to copy the elements. </param>
		/// <param name="i">The starting index of <paramref name="array" />. </param>
		/// <exception cref="T:System.ArgumentException">The sum of <paramref name="index" /> and the number of elements in the <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> is greater than the length of the array. </exception>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="array" /> is null. </exception>
		/// <exception cref="T:System.ArgumentOutOfRangeException">The <paramref name="index" /> is not valid for <paramref name="array" />. </exception>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06001075 RID: 4213 RVA: 0x00040C78 File Offset: 0x0003EE78
		public void CopyTo(Array array, int i)
		{
			if (array == null)
			{
				throw new ArgumentNullException("array");
			}
			if (i < array.GetLowerBound(0) || i > array.GetUpperBound(0))
			{
				throw new ArgumentOutOfRangeException("index");
			}
			if (array.IsFixedSize || i + this.Count > array.GetUpperBound(0))
			{
				throw new ArgumentException("array");
			}
			((OdbcError[])this._items.ToArray()).CopyTo(array, i);
		}

		/// <summary>Returns an object that implements the <see cref="T:" /><see cref="System.Collections.IEnumerator" /> interface and that can iterate through the <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> objects in the <see cref="T:System.Data.Odbc.OdbcErrorCollection" />.</summary>
		/// <returns>An object that implements the <see cref="T:" /><see cref="System.Collections.IEnumerator" /> interface and that can iterate through the <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> objects in the <see cref="T:System.Data.Odbc.OdbcErrorCollection" />.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06001076 RID: 4214 RVA: 0x00040CFC File Offset: 0x0003EEFC
		public IEnumerator GetEnumerator()
		{
			return this._items.GetEnumerator();
		}

		/// <summary>Copies all the elements of the current <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> to the specified <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> starting at the specified destination index.</summary>
		/// <param name="array">The <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> that is the destination of the elements copied from the current <see cref="T:System.Data.Odbc.OdbcErrorCollection" />.</param>
		/// <param name="i">A 32-bit integer that represents the index in the <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> at which copying starts.</param>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06001077 RID: 4215 RVA: 0x00040D0C File Offset: 0x0003EF0C
		public void CopyTo(OdbcError[] array, int index)
		{
			if (array == null)
			{
				throw new ArgumentNullException("array");
			}
			if (index < array.GetLowerBound(0) || index > array.GetUpperBound(0))
			{
				throw new ArgumentOutOfRangeException("index");
			}
			((OdbcError[])this._items.ToArray()).CopyTo(array, index);
		}

		// Token: 0x0400056B RID: 1387
		private readonly ArrayList _items = new ArrayList();
	}
}
