using System;
using System.Data.Common;
using System.Runtime.Serialization;
using System.Text;

namespace System.Data.Odbc
{
	/// <summary>The exception that is generated when a warning or error is returned by an ODBC data source. This class cannot be inherited.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x02000124 RID: 292
	[Serializable]
	public sealed class OdbcException : DbException
	{
		// Token: 0x06001078 RID: 4216 RVA: 0x00040D68 File Offset: 0x0003EF68
		internal OdbcException(OdbcErrorCollection errors)
			: base(OdbcException.CreateMessage(errors))
		{
			this.odbcErrors = errors;
		}

		// Token: 0x06001079 RID: 4217 RVA: 0x00040D80 File Offset: 0x0003EF80
		private OdbcException(SerializationInfo si, StreamingContext sc)
			: base(si, sc)
		{
			this.odbcErrors = new OdbcErrorCollection();
			this.odbcErrors = (OdbcErrorCollection)si.GetValue("odbcErrors", typeof(OdbcErrorCollection));
		}

		/// <summary>Gets a collection of one or more <see cref="T:System.Data.Odbc.OdbcError" /> objects that give detailed information about exceptions generated by the .NET Framework Data Provider for ODBC.</summary>
		/// <returns>The collected instances of the <see cref="T:System.Data.Odbc.OdbcError" /> class.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170002C7 RID: 711
		// (get) Token: 0x0600107A RID: 4218 RVA: 0x00040DB8 File Offset: 0x0003EFB8
		public OdbcErrorCollection Errors
		{
			get
			{
				return this.odbcErrors;
			}
		}

		/// <summary>Gets the name of the ODBC driver that generated the error.</summary>
		/// <returns>The name of the ODBC driver that generated the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170002C8 RID: 712
		// (get) Token: 0x0600107B RID: 4219 RVA: 0x00040DC0 File Offset: 0x0003EFC0
		public override string Source
		{
			get
			{
				return this.odbcErrors[0].Source;
			}
		}

		/// <summary>This member overrides <see cref="M:System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />.</summary>
		/// <param name="si">The <see cref="T:System.Runtime.Serialization.SerializationInfo" /> that holds the serialized object data about the exception being thrown.</param>
		/// <param name="context">The <see cref="T:System.Runtime.Serialization.StreamingContext" /> that contains contextual information about the source or destination.</param>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="si" /> parameter is a null reference (Nothing in Visual Basic).</exception>
		/// <filterpriority>2</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
		///   <IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="ControlEvidence, SerializationFormatter" />
		/// </PermissionSet>
		// Token: 0x0600107C RID: 4220 RVA: 0x00040DD4 File Offset: 0x0003EFD4
		public override void GetObjectData(SerializationInfo si, StreamingContext context)
		{
			if (si == null)
			{
				throw new ArgumentNullException("si");
			}
			si.AddValue("odbcErrors", this.odbcErrors, typeof(OdbcErrorCollection));
			base.GetObjectData(si, context);
		}

		// Token: 0x0600107D RID: 4221 RVA: 0x00040E18 File Offset: 0x0003F018
		private static string CreateMessage(OdbcErrorCollection errors)
		{
			StringBuilder stringBuilder = new StringBuilder();
			for (int i = 0; i < errors.Count; i++)
			{
				if (i > 0)
				{
					stringBuilder.Append(Environment.NewLine);
				}
				OdbcError odbcError = errors[i];
				stringBuilder.AppendFormat("ERROR [{0}] {1}", odbcError.SQLState, odbcError.Message);
			}
			return stringBuilder.ToString();
		}

		// Token: 0x0400056C RID: 1388
		private OdbcErrorCollection odbcErrors;
	}
}
