using System;
using System.ComponentModel;

namespace System.Text.RegularExpressions
{
	/// <summary>The <see cref="T:System.Text.RegularExpressions.RegexRunner" /> class is the base class for compiled regular expressions.</summary>
	// Token: 0x0200048D RID: 1165
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.MonoTODO("RegexRunner is not supported by Mono.")]
	public abstract class RegexRunner
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Text.RegularExpressions.RegexRunner" /> class. </summary>
		// Token: 0x060029DE RID: 10718 RVA: 0x0008BC58 File Offset: 0x00089E58
		[global::System.MonoTODO]
		protected internal RegexRunner()
		{
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029DF RID: 10719
		protected abstract bool FindFirstChar();

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E0 RID: 10720
		protected abstract void Go();

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E1 RID: 10721
		protected abstract void InitTrackCount();

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E2 RID: 10722 RVA: 0x0008BC60 File Offset: 0x00089E60
		[global::System.MonoTODO]
		protected void Capture(int capnum, int start, int end)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. Determines whether a character is in a character class.</summary>
		/// <returns>true if the <paramref name="ch" /> parameter is in the character class specified by the <paramref name="charClass" /> parameter.</returns>
		/// <param name="ch">A character to test.</param>
		/// <param name="charClass">The internal name of a character class.</param>
		// Token: 0x060029E3 RID: 10723 RVA: 0x0008BC68 File Offset: 0x00089E68
		[global::System.MonoTODO]
		protected static bool CharInClass(char ch, string charClass)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E4 RID: 10724 RVA: 0x0008BC70 File Offset: 0x00089E70
		[global::System.MonoTODO]
		protected static bool CharInSet(char ch, string set, string category)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E5 RID: 10725 RVA: 0x0008BC78 File Offset: 0x00089E78
		[global::System.MonoTODO]
		protected void Crawl(int i)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E6 RID: 10726 RVA: 0x0008BC80 File Offset: 0x00089E80
		[global::System.MonoTODO]
		protected int Crawlpos()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E7 RID: 10727 RVA: 0x0008BC88 File Offset: 0x00089E88
		[global::System.MonoTODO]
		protected void DoubleCrawl()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E8 RID: 10728 RVA: 0x0008BC90 File Offset: 0x00089E90
		[global::System.MonoTODO]
		protected void DoubleStack()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E9 RID: 10729 RVA: 0x0008BC98 File Offset: 0x00089E98
		[global::System.MonoTODO]
		protected void DoubleTrack()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029EA RID: 10730 RVA: 0x0008BCA0 File Offset: 0x00089EA0
		[global::System.MonoTODO]
		protected void EnsureStorage()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029EB RID: 10731 RVA: 0x0008BCA8 File Offset: 0x00089EA8
		[global::System.MonoTODO]
		protected bool IsBoundary(int index, int startpos, int endpos)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029EC RID: 10732 RVA: 0x0008BCB0 File Offset: 0x00089EB0
		[global::System.MonoTODO]
		protected bool IsECMABoundary(int index, int startpos, int endpos)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029ED RID: 10733 RVA: 0x0008BCB8 File Offset: 0x00089EB8
		[global::System.MonoTODO]
		protected bool IsMatched(int cap)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029EE RID: 10734 RVA: 0x0008BCC0 File Offset: 0x00089EC0
		[global::System.MonoTODO]
		protected int MatchIndex(int cap)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029EF RID: 10735 RVA: 0x0008BCC8 File Offset: 0x00089EC8
		[global::System.MonoTODO]
		protected int MatchLength(int cap)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029F0 RID: 10736 RVA: 0x0008BCD0 File Offset: 0x00089ED0
		[global::System.MonoTODO]
		protected int Popcrawl()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029F1 RID: 10737 RVA: 0x0008BCD8 File Offset: 0x00089ED8
		[global::System.MonoTODO]
		protected void TransferCapture(int capnum, int uncapnum, int start, int end)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x060029F2 RID: 10738 RVA: 0x0008BCE0 File Offset: 0x00089EE0
		[global::System.MonoTODO]
		protected void Uncapture()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029F3 RID: 10739 RVA: 0x0008BCE8 File Offset: 0x00089EE8
		protected internal Match Scan(Regex regex, string text, int textbeg, int textend, int textstart, int prevlen, bool quick)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A2A RID: 6698
		[global::System.MonoTODO]
		protected internal int[] runcrawl;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A2B RID: 6699
		[global::System.MonoTODO]
		protected internal int runcrawlpos;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A2C RID: 6700
		[global::System.MonoTODO]
		protected internal Match runmatch;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A2D RID: 6701
		[global::System.MonoTODO]
		protected internal Regex runregex;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A2E RID: 6702
		[global::System.MonoTODO]
		protected internal int[] runstack;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A2F RID: 6703
		[global::System.MonoTODO]
		protected internal int runstackpos;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A30 RID: 6704
		[global::System.MonoTODO]
		protected internal string runtext;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A31 RID: 6705
		[global::System.MonoTODO]
		protected internal int runtextbeg;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A32 RID: 6706
		[global::System.MonoTODO]
		protected internal int runtextend;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A33 RID: 6707
		[global::System.MonoTODO]
		protected internal int runtextpos;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A34 RID: 6708
		[global::System.MonoTODO]
		protected internal int runtextstart;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A35 RID: 6709
		[global::System.MonoTODO]
		protected internal int[] runtrack;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A36 RID: 6710
		[global::System.MonoTODO]
		protected internal int runtrackcount;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A37 RID: 6711
		[global::System.MonoTODO]
		protected internal int runtrackpos;
	}
}
