using System;
using System.Collections;
using System.ComponentModel;

namespace System.Data.SqlClient
{
	/// <summary>Collects all errors generated by the .NET Framework Data Provider for SQL Server. This class cannot be inherited. </summary>
	/// <filterpriority>1</filterpriority>
	// Token: 0x0200016C RID: 364
	[ListBindable(false)]
	[Serializable]
	public sealed class SqlErrorCollection : IEnumerable, ICollection
	{
		// Token: 0x0600137C RID: 4988 RVA: 0x00051800 File Offset: 0x0004FA00
		internal SqlErrorCollection()
		{
		}

		// Token: 0x0600137D RID: 4989 RVA: 0x00051814 File Offset: 0x0004FA14
		internal SqlErrorCollection(byte theClass, int lineNumber, string message, int number, string procedure, string server, string source, byte state)
		{
			this.Add(theClass, lineNumber, message, number, procedure, server, source, state);
		}

		// Token: 0x1700038F RID: 911
		// (get) Token: 0x0600137E RID: 4990 RVA: 0x00051848 File Offset: 0x0004FA48
		bool ICollection.IsSynchronized
		{
			get
			{
				return this.list.IsSynchronized;
			}
		}

		// Token: 0x17000390 RID: 912
		// (get) Token: 0x0600137F RID: 4991 RVA: 0x00051858 File Offset: 0x0004FA58
		object ICollection.SyncRoot
		{
			get
			{
				return this.list.SyncRoot;
			}
		}

		/// <summary>Gets the number of errors in the collection.</summary>
		/// <returns>The total number of errors in the collection.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000391 RID: 913
		// (get) Token: 0x06001380 RID: 4992 RVA: 0x00051868 File Offset: 0x0004FA68
		public int Count
		{
			get
			{
				return this.list.Count;
			}
		}

		/// <summary>Gets the error at the specified index.</summary>
		/// <returns>A <see cref="T:System.Data.SqlClient.SqlError" /> that contains the error at the specified index.</returns>
		/// <param name="index">The zero-based index of the error to retrieve. </param>
		/// <exception cref="T:System.IndexOutOfRangeException">Index parameter is outside array bounds. </exception>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000392 RID: 914
		public SqlError this[int index]
		{
			get
			{
				return (SqlError)this.list[index];
			}
		}

		// Token: 0x06001382 RID: 4994 RVA: 0x0005188C File Offset: 0x0004FA8C
		internal void Add(SqlError error)
		{
			this.list.Add(error);
		}

		// Token: 0x06001383 RID: 4995 RVA: 0x0005189C File Offset: 0x0004FA9C
		internal void Add(byte theClass, int lineNumber, string message, int number, string procedure, string server, string source, byte state)
		{
			SqlError sqlError = new SqlError(theClass, lineNumber, message, number, procedure, server, source, state);
			this.Add(sqlError);
		}

		/// <summary>Copies the elements of the <see cref="T:System.Data.SqlClient.SqlErrorCollection" /> collection into an <see cref="T:System.Array" />, starting at the specified index.</summary>
		/// <param name="array">The <see cref="T:System.Array" /> to copy elements into. </param>
		/// <param name="index">The index from which to start copying into the <paramref name="array" /> parameter. </param>
		/// <exception cref="T:System.ArgumentException">The sum of <paramref name="index" /> and the number of elements in the <see cref="T:System.Data.SqlClient.SqlErrorCollection" /> collection is greater than the <see cref="P:System.Array.Length" /> of the <see cref="T:System.Array" />. </exception>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="array" /> is null. </exception>
		/// <exception cref="T:System.ArgumentOutOfRangeException">The <paramref name="index" /> is not valid for <paramref name="array" />. </exception>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06001384 RID: 4996 RVA: 0x000518C4 File Offset: 0x0004FAC4
		public void CopyTo(Array array, int index)
		{
			this.list.CopyTo(array, index);
		}

		/// <summary>Returns an enumerator that iterates through the <see cref="T:System.Data.SqlClient.SqlErrorCollection" />.</summary>
		/// <returns>An <see cref="T:System.Collections.IEnumerator" /> for the <see cref="T:System.Data.SqlClient.SqlErrorCollection" />.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06001385 RID: 4997 RVA: 0x000518D4 File Offset: 0x0004FAD4
		public IEnumerator GetEnumerator()
		{
			return this.list.GetEnumerator();
		}

		/// <summary>Copies the elements of the <see cref="T:System.Data.SqlClient.SqlErrorCollection" /> collection into a <see cref="T:System.Data.SqlClient.SqlErrorCollection" />, starting at the specified index.</summary>
		/// <param name="array">The <see cref="T:System.Data.SqlClient.SqlErrorCollection" /> to copy the elements into.</param>
		/// <param name="index">The index from which to start copying into the <paramref name="array" /> parameter.</param>
		/// <exception cref="T:System.ArgumentException">The sum of <paramref name="index" /> and the number of elements in the <see cref="T:System.Data.SqlClient.SqlErrorCollection" /> collection is greater than the length of the <see cref="T:System.Data.SqlClient.SqlErrorCollection" />. </exception>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="array" /> is null. </exception>
		/// <exception cref="T:System.ArgumentOutOfRangeException">The <paramref name="index" /> is not valid for <paramref name="array" />. </exception>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06001386 RID: 4998 RVA: 0x000518E4 File Offset: 0x0004FAE4
		public void CopyTo(SqlError[] array, int index)
		{
			this.list.CopyTo(array, index);
		}

		// Token: 0x040007EA RID: 2026
		private ArrayList list = new ArrayList();
	}
}
