using System;
using System.ComponentModel;
using System.Data.Common;
using System.Runtime.Serialization;
using System.Text;
using Mono.Data.Tds.Protocol;

namespace System.Data.SqlClient
{
	/// <summary>The exception that is thrown when SQL Server returns a warning or error. This class cannot be inherited.</summary>
	/// <filterpriority>1</filterpriority>
	// Token: 0x0200016D RID: 365
	[Serializable]
	public sealed class SqlException : DbException
	{
		// Token: 0x06001387 RID: 4999 RVA: 0x000518F4 File Offset: 0x0004FAF4
		internal SqlException()
			: this("SQL Exception has occured.", null, null)
		{
		}

		// Token: 0x06001388 RID: 5000 RVA: 0x00051904 File Offset: 0x0004FB04
		internal SqlException(string message, Exception inner)
			: this(message, inner, null)
		{
		}

		// Token: 0x06001389 RID: 5001 RVA: 0x00051910 File Offset: 0x0004FB10
		internal SqlException(string message, Exception inner, SqlError sqlError)
			: base((message != null) ? message : "SQL Exception has occured.", inner)
		{
			base.HResult = -2146232060;
			this.errors = new SqlErrorCollection();
			if (sqlError != null)
			{
				this.errors.Add(sqlError);
			}
		}

		// Token: 0x0600138A RID: 5002 RVA: 0x00051960 File Offset: 0x0004FB60
		internal SqlException(byte theClass, int lineNumber, string message, int number, string procedure, string server, string source, byte state)
			: this(null, null, new SqlError(theClass, lineNumber, message, number, procedure, server, source, state))
		{
		}

		// Token: 0x0600138B RID: 5003 RVA: 0x00051988 File Offset: 0x0004FB88
		private SqlException(SerializationInfo si, StreamingContext sc)
		{
			base.HResult = -2146232060;
			this.errors = (SqlErrorCollection)si.GetValue("Errors", typeof(SqlErrorCollection));
		}

		/// <summary>Gets the severity level of the error returned from the .NET Framework Data Provider for SQL Server.</summary>
		/// <returns>A value from 1 to 25 that indicates the severity level of the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000393 RID: 915
		// (get) Token: 0x0600138C RID: 5004 RVA: 0x000519C8 File Offset: 0x0004FBC8
		public byte Class
		{
			get
			{
				return this.Errors[0].Class;
			}
		}

		/// <summary>Gets a collection of one or more <see cref="T:System.Data.SqlClient.SqlError" /> objects that give detailed information about exceptions generated by the .NET Framework Data Provider for SQL Server.</summary>
		/// <returns>The collected instances of the <see cref="T:System.Data.SqlClient.SqlError" /> class.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000394 RID: 916
		// (get) Token: 0x0600138D RID: 5005 RVA: 0x000519DC File Offset: 0x0004FBDC
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		public SqlErrorCollection Errors
		{
			get
			{
				return this.errors;
			}
		}

		/// <summary>Gets the line number within the Transact-SQL command batch or stored procedure that generated the error.</summary>
		/// <returns>The line number within the Transact-SQL command batch or stored procedure that generated the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000395 RID: 917
		// (get) Token: 0x0600138E RID: 5006 RVA: 0x000519E4 File Offset: 0x0004FBE4
		public int LineNumber
		{
			get
			{
				return this.Errors[0].LineNumber;
			}
		}

		// Token: 0x17000396 RID: 918
		// (get) Token: 0x0600138F RID: 5007 RVA: 0x000519F8 File Offset: 0x0004FBF8
		public override string Message
		{
			get
			{
				if (this.Errors.Count == 0)
				{
					return base.Message;
				}
				StringBuilder stringBuilder = new StringBuilder();
				if (base.Message != "SQL Exception has occured.")
				{
					stringBuilder.Append(base.Message);
					stringBuilder.Append("\n");
				}
				for (int i = 0; i < this.Errors.Count - 1; i++)
				{
					stringBuilder.Append(this.Errors[i].Message);
					stringBuilder.Append("\n");
				}
				stringBuilder.Append(this.Errors[this.Errors.Count - 1].Message);
				return stringBuilder.ToString();
			}
		}

		/// <summary>Gets a number that identifies the type of error.</summary>
		/// <returns>The number that identifies the type of error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000397 RID: 919
		// (get) Token: 0x06001390 RID: 5008 RVA: 0x00051ABC File Offset: 0x0004FCBC
		public int Number
		{
			get
			{
				return this.Errors[0].Number;
			}
		}

		/// <summary>Gets the name of the stored procedure or remote procedure call (RPC) that generated the error.</summary>
		/// <returns>The name of the stored procedure or RPC.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000398 RID: 920
		// (get) Token: 0x06001391 RID: 5009 RVA: 0x00051AD0 File Offset: 0x0004FCD0
		public string Procedure
		{
			get
			{
				return this.Errors[0].Procedure;
			}
		}

		/// <summary>Gets the name of the computer that is running an instance of SQL Server that generated the error.</summary>
		/// <returns>The name of the computer running an instance of SQL Server.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000399 RID: 921
		// (get) Token: 0x06001392 RID: 5010 RVA: 0x00051AE4 File Offset: 0x0004FCE4
		public string Server
		{
			get
			{
				return this.Errors[0].Server;
			}
		}

		/// <summary>Gets the name of the provider that generated the error.</summary>
		/// <returns>The name of the provider that generated the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x1700039A RID: 922
		// (get) Token: 0x06001393 RID: 5011 RVA: 0x00051AF8 File Offset: 0x0004FCF8
		public override string Source
		{
			get
			{
				return this.Errors[0].Source;
			}
		}

		/// <summary>Gets a numeric error code from SQL Server that represents an error, warning or "no data found" message. For more information about how to decode these values, see SQL Server Books Online.</summary>
		/// <returns>The number representing the error code.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x1700039B RID: 923
		// (get) Token: 0x06001394 RID: 5012 RVA: 0x00051B0C File Offset: 0x0004FD0C
		public byte State
		{
			get
			{
				return this.Errors[0].State;
			}
		}

		// Token: 0x06001395 RID: 5013 RVA: 0x00051B20 File Offset: 0x0004FD20
		internal static SqlException FromTdsInternalException(TdsInternalException e)
		{
			SqlError sqlError = new SqlError(e.Class, e.LineNumber, e.Message, e.Number, e.Procedure, e.Server, "Mono SqlClient Data Provider", e.State);
			return new SqlException(null, e, sqlError);
		}

		/// <summary>Sets the <see cref="T:System.Runtime.Serialization.SerializationInfo" /> with information about the exception.</summary>
		/// <param name="si">The <see cref="T:System.Runtime.Serialization.SerializationInfo" /> that holds the serialized object data about the exception being thrown. </param>
		/// <param name="context">The <see cref="T:System.Runtime.Serialization.StreamingContext" /> that contains contextual information about the source or destination.</param>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="si" /> parameter is a null reference (Nothing in Visual Basic).</exception>
		/// <filterpriority>2</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
		///   <IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="ControlEvidence, SerializationFormatter" />
		/// </PermissionSet>
		// Token: 0x06001396 RID: 5014 RVA: 0x00051B6C File Offset: 0x0004FD6C
		public override void GetObjectData(SerializationInfo si, StreamingContext context)
		{
			if (si == null)
			{
				throw new ArgumentNullException("si");
			}
			si.AddValue("Errors", this.errors, typeof(SqlErrorCollection));
			base.GetObjectData(si, context);
		}

		// Token: 0x040007EB RID: 2027
		private const string DEF_MESSAGE = "SQL Exception has occured.";

		// Token: 0x040007EC RID: 2028
		private readonly SqlErrorCollection errors;
	}
}
