using System;

namespace System.Data.SqlClient
{
	/// <summary>Collects information relevant to a warning or error returned by SQL Server.</summary>
	/// <filterpriority>1</filterpriority>
	// Token: 0x0200016B RID: 363
	[Serializable]
	public sealed class SqlError
	{
		// Token: 0x06001372 RID: 4978 RVA: 0x0005173C File Offset: 0x0004F93C
		internal SqlError(byte errorClass, int lineNumber, string message, int number, string procedure, string server, string source, byte state)
		{
			this.errorClass = errorClass;
			this.lineNumber = lineNumber;
			this.message = message;
			this.number = number;
			this.procedure = procedure;
			this.server = server;
			this.source = source;
			this.state = state;
		}

		/// <summary>Gets the severity level of the error returned from SQL Server.</summary>
		/// <returns>A value from 1 to 25 that indicates the severity level of the error. The default is 0.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000387 RID: 903
		// (get) Token: 0x06001373 RID: 4979 RVA: 0x000517B8 File Offset: 0x0004F9B8
		public byte Class
		{
			get
			{
				return this.errorClass;
			}
		}

		/// <summary>Gets the line number within the Transact-SQL command batch or stored procedure that contains the error.</summary>
		/// <returns>The line number within the Transact-SQL command batch or stored procedure that contains the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000388 RID: 904
		// (get) Token: 0x06001374 RID: 4980 RVA: 0x000517C0 File Offset: 0x0004F9C0
		public int LineNumber
		{
			get
			{
				return this.lineNumber;
			}
		}

		/// <summary>Gets the text describing the error.</summary>
		/// <returns>The text describing the error.For more information on errors generated by SQL Server, see SQL Server Books Online.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000389 RID: 905
		// (get) Token: 0x06001375 RID: 4981 RVA: 0x000517C8 File Offset: 0x0004F9C8
		public string Message
		{
			get
			{
				return this.message;
			}
		}

		/// <summary>Gets a number that identifies the type of error.</summary>
		/// <returns>The number that identifies the type of error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x1700038A RID: 906
		// (get) Token: 0x06001376 RID: 4982 RVA: 0x000517D0 File Offset: 0x0004F9D0
		public int Number
		{
			get
			{
				return this.number;
			}
		}

		/// <summary>Gets the name of the stored procedure or remote procedure call (RPC) that generated the error.</summary>
		/// <returns>The name of the stored procedure or RPC.For more information on errors generated by SQL Server, see SQL Server Books Online.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x1700038B RID: 907
		// (get) Token: 0x06001377 RID: 4983 RVA: 0x000517D8 File Offset: 0x0004F9D8
		public string Procedure
		{
			get
			{
				return this.procedure;
			}
		}

		/// <summary>Gets the name of the instance of SQL Server that generated the error.</summary>
		/// <returns>The name of the instance of SQL Server.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x1700038C RID: 908
		// (get) Token: 0x06001378 RID: 4984 RVA: 0x000517E0 File Offset: 0x0004F9E0
		public string Server
		{
			get
			{
				return this.server;
			}
		}

		/// <summary>Gets the name of the provider that generated the error.</summary>
		/// <returns>The name of the provider that generated the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x1700038D RID: 909
		// (get) Token: 0x06001379 RID: 4985 RVA: 0x000517E8 File Offset: 0x0004F9E8
		public string Source
		{
			get
			{
				return this.source;
			}
		}

		/// <summary>Gets a numeric error code from SQL Server that represents an error, warning or "no data found" message.</summary>
		/// <returns>The number that represents the error code.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x1700038E RID: 910
		// (get) Token: 0x0600137A RID: 4986 RVA: 0x000517F0 File Offset: 0x0004F9F0
		public byte State
		{
			get
			{
				return this.state;
			}
		}

		/// <summary>Gets the complete text of the error message.</summary>
		/// <returns>The complete text of the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x0600137B RID: 4987 RVA: 0x000517F8 File Offset: 0x0004F9F8
		public override string ToString()
		{
			return this.Message;
		}

		// Token: 0x040007E2 RID: 2018
		private byte errorClass;

		// Token: 0x040007E3 RID: 2019
		private int lineNumber;

		// Token: 0x040007E4 RID: 2020
		private string message = string.Empty;

		// Token: 0x040007E5 RID: 2021
		private int number;

		// Token: 0x040007E6 RID: 2022
		private string procedure = string.Empty;

		// Token: 0x040007E7 RID: 2023
		private string source = string.Empty;

		// Token: 0x040007E8 RID: 2024
		private byte state;

		// Token: 0x040007E9 RID: 2025
		[NonSerialized]
		private string server = string.Empty;
	}
}
