using System;
using System.Collections;
using System.ComponentModel;

namespace System.Data.OleDb
{
	/// <summary>Collects all errors generated by the .NET Framework Data Provider for OLE DB. This class cannot be inherited.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x020000F0 RID: 240
	[ListBindable(false)]
	[Serializable]
	public sealed class OleDbErrorCollection : IEnumerable, ICollection
	{
		// Token: 0x06000BB1 RID: 2993 RVA: 0x000333D0 File Offset: 0x000315D0
		internal OleDbErrorCollection()
		{
		}

		/// <summary>For a description of this member, see <see cref="M:System.Collections.ICollection.SyncRoot" />.</summary>
		// Token: 0x17000229 RID: 553
		// (get) Token: 0x06000BB2 RID: 2994 RVA: 0x000333D8 File Offset: 0x000315D8
		object ICollection.SyncRoot
		{
			get
			{
				return this.items.SyncRoot;
			}
		}

		/// <summary>For a description of this member, see <see cref="M:System.Collections.ICollection.IsSynchronized" />.</summary>
		// Token: 0x1700022A RID: 554
		// (get) Token: 0x06000BB3 RID: 2995 RVA: 0x000333E8 File Offset: 0x000315E8
		bool ICollection.IsSynchronized
		{
			get
			{
				return this.items.IsSynchronized;
			}
		}

		/// <summary>Gets the number of errors in the collection.</summary>
		/// <returns>The total number of errors in the collection.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x1700022B RID: 555
		// (get) Token: 0x06000BB4 RID: 2996 RVA: 0x000333F8 File Offset: 0x000315F8
		public int Count
		{
			get
			{
				return this.items.Count;
			}
		}

		/// <summary>Gets the error at the specified index.</summary>
		/// <returns>An <see cref="T:System.Data.OleDb.OleDbError" /> that contains the error at the specified index.</returns>
		/// <param name="index">The zero-based index of the error to retrieve. </param>
		/// <filterpriority>2</filterpriority>
		// Token: 0x1700022C RID: 556
		public OleDbError this[int index]
		{
			get
			{
				return (OleDbError)this.items[index];
			}
		}

		// Token: 0x06000BB6 RID: 2998 RVA: 0x0003341C File Offset: 0x0003161C
		internal void Add(OleDbError error)
		{
			this.items.Add(error);
		}

		/// <summary>Copies the elements of the <see cref="T:System.Data.OleDb.OleDbErrorCollection" /> into an <see cref="T:System.Array" />, starting at the specified index within the <see cref="T:System.Array" />.</summary>
		/// <param name="array">The <see cref="T:System.Array" /> into which to copy the elements. </param>
		/// <param name="index">The starting index of the <paramref name="array" />. </param>
		/// <exception cref="T:System.ArgumentException">The sum of <paramref name="index" /> and the number of elements in the <see cref="T:System.Data.OleDb.OleDbErrorCollection" /> is greater than the length of the <see cref="T:System.Array" />. </exception>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="array" /> is null. </exception>
		/// <exception cref="T:System.ArgumentOutOfRangeException">The <paramref name="index" /> is not valid for <paramref name="array" />. </exception>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06000BB7 RID: 2999 RVA: 0x0003342C File Offset: 0x0003162C
		public void CopyTo(Array array, int index)
		{
			if (array == null)
			{
				throw new ArgumentNullException("array");
			}
			if (index < array.GetLowerBound(0) || index > array.GetUpperBound(0))
			{
				throw new ArgumentOutOfRangeException("index");
			}
			if (array.IsFixedSize || index + this.Count > array.GetUpperBound(0))
			{
				throw new ArgumentException("array");
			}
			((OleDbError[])this.items.ToArray()).CopyTo(array, index);
		}

		/// <summary>Copies all the elements of the current <see cref="T:System.Data.OleDb.OleDbErrorCollection" /> to the specified <see cref="T:System.Data.OleDb.OleDbErrorCollection" /> starting at the specified destination index.</summary>
		/// <param name="array">The <see cref="T:System.Data.OleDb.OleDbErrorCollection" /> that is the destination of the elements copied from the current <see cref="T:System.Data.OleDb.OleDbErrorCollection" />. </param>
		/// <param name="index">A 32-bit integer that represents the index in the <see cref="T:System.Data.OleDb.OleDbErrorCollection" /> at which copying starts.</param>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06000BB8 RID: 3000 RVA: 0x000334B0 File Offset: 0x000316B0
		public void CopyTo(OleDbError[] array, int index)
		{
			this.items.CopyTo(array, index);
		}

		/// <summary>Exposes the <see cref="M:System.Collections.IEnumerable.GetEnumerator" /> method, which supports a simple iteration over a collection by a .NET Framework data provider.</summary>
		/// <returns>An <see cref="T:System.Collections.IEnumerator" /> that can be used to iterate through the collection.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06000BB9 RID: 3001 RVA: 0x000334C0 File Offset: 0x000316C0
		public IEnumerator GetEnumerator()
		{
			return this.items.GetEnumerator();
		}

		// Token: 0x0400043B RID: 1083
		private ArrayList items;
	}
}
