using System;
using System.ComponentModel;
using System.Data.Common;
using System.Globalization;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;

namespace System.Data.OleDb
{
	/// <summary>The exception that is thrown when the underlying provider returns a warning or error for an OLE DB data source. This class cannot be inherited.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x020000F1 RID: 241
	[Serializable]
	public sealed class OleDbException : DbException
	{
		// Token: 0x06000BBA RID: 3002 RVA: 0x000334D0 File Offset: 0x000316D0
		internal OleDbException(OleDbConnection cnc)
		{
			this.connection = cnc;
		}

		/// <summary>Gets the HRESULT of the error.</summary>
		/// <returns>The HRESULT of the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x1700022D RID: 557
		// (get) Token: 0x06000BBB RID: 3003 RVA: 0x000334E0 File Offset: 0x000316E0
		[TypeConverter(typeof(OleDbException.ErrorCodeConverter))]
		public override int ErrorCode
		{
			get
			{
				IntPtr intPtr = libgda.gda_connection_get_errors(this.connection.GdaConnection);
				if (intPtr != IntPtr.Zero)
				{
					GdaList gdaList = (GdaList)Marshal.PtrToStructure(intPtr, typeof(GdaList));
					return (int)libgda.gda_error_get_number(gdaList.data);
				}
				return -1;
			}
		}

		/// <summary>Gets a collection of one or more <see cref="T:System.Data.OleDb.OleDbError" /> objects that give detailed information about exceptions generated by the .NET Framework Data Provider for OLE DB.</summary>
		/// <returns>The collected instances of the <see cref="T:System.Data.OleDb.OleDbError" /> class.</returns>
		/// <filterpriority>2</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="UnmanagedCode, ControlEvidence" />
		/// </PermissionSet>
		// Token: 0x1700022E RID: 558
		// (get) Token: 0x06000BBC RID: 3004 RVA: 0x00033534 File Offset: 0x00031734
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		public OleDbErrorCollection Errors
		{
			get
			{
				OleDbErrorCollection oleDbErrorCollection = new OleDbErrorCollection();
				IntPtr intPtr = libgda.gda_connection_get_errors(this.connection.GdaConnection);
				if (intPtr != IntPtr.Zero)
				{
					for (GdaList gdaList = (GdaList)Marshal.PtrToStructure(intPtr, typeof(GdaList)); gdaList != null; gdaList = (GdaList)Marshal.PtrToStructure(gdaList.next, typeof(GdaList)))
					{
						oleDbErrorCollection.Add(new OleDbError(libgda.gda_error_get_description(gdaList.data), (int)libgda.gda_error_get_number(gdaList.data), libgda.gda_error_get_source(gdaList.data), libgda.gda_error_get_sqlstate(gdaList.data)));
					}
				}
				return oleDbErrorCollection;
			}
		}

		// Token: 0x1700022F RID: 559
		// (get) Token: 0x06000BBD RID: 3005 RVA: 0x000335E0 File Offset: 0x000317E0
		public new string Message
		{
			get
			{
				string text = string.Empty;
				IntPtr intPtr = libgda.gda_connection_get_errors(this.connection.GdaConnection);
				if (intPtr != IntPtr.Zero)
				{
					for (GdaList gdaList = (GdaList)Marshal.PtrToStructure(intPtr, typeof(GdaList)); gdaList != null; gdaList = (GdaList)Marshal.PtrToStructure(gdaList.next, typeof(GdaList)))
					{
						text = text + ";" + libgda.gda_error_get_description(gdaList.data);
					}
					return text;
				}
				return null;
			}
		}

		// Token: 0x17000230 RID: 560
		// (get) Token: 0x06000BBE RID: 3006 RVA: 0x0003366C File Offset: 0x0003186C
		public new string Source
		{
			get
			{
				IntPtr intPtr = libgda.gda_connection_get_errors(this.connection.GdaConnection);
				if (intPtr != IntPtr.Zero)
				{
					GdaList gdaList = (GdaList)Marshal.PtrToStructure(intPtr, typeof(GdaList));
					return libgda.gda_error_get_source(gdaList.data);
				}
				return null;
			}
		}

		/// <summary>This member overrides <see cref="M:System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />.</summary>
		/// <param name="si">The <see cref="T:System.Runtime.Serialization.SerializationInfo" /> that holds the serialized object data about the exception being thrown.</param>
		/// <param name="context">The <see cref="T:System.Runtime.Serialization.StreamingContext" /> that contains contextual information about the source or destination.</param>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="si" /> parameter is a null reference (Nothing in Visual Basic).</exception>
		/// <filterpriority>2</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
		///   <IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="ControlEvidence, SerializationFormatter" />
		/// </PermissionSet>
		// Token: 0x06000BBF RID: 3007 RVA: 0x000336C0 File Offset: 0x000318C0
		public override void GetObjectData(SerializationInfo si, StreamingContext context)
		{
			if (si == null)
			{
				throw new ArgumentNullException("si");
			}
			si.AddValue("connection", this.connection);
			base.GetObjectData(si, context);
			throw new NotImplementedException();
		}

		// Token: 0x0400043C RID: 1084
		private OleDbConnection connection;

		// Token: 0x020000F2 RID: 242
		internal sealed class ErrorCodeConverter : Int32Converter
		{
			// Token: 0x06000BC1 RID: 3009 RVA: 0x000336FC File Offset: 0x000318FC
			[MonoTODO]
			public override object ConvertTo(ITypeDescriptorContext context, CultureInfo culture, object value, Type destinationType)
			{
				return base.ConvertTo(context, culture, value, destinationType);
			}
		}
	}
}
