using System;

namespace System.Data.Common
{
	/// <summary>Provides the data for the RowUpdating event of a .NET Framework data provider.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x020000DA RID: 218
	public class RowUpdatingEventArgs : EventArgs
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Data.Common.RowUpdatingEventArgs" /> class.</summary>
		/// <param name="dataRow">The <see cref="T:System.Data.DataRow" /> to <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />. </param>
		/// <param name="command">The <see cref="T:System.Data.IDbCommand" /> to execute when <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" /> is called. </param>
		/// <param name="statementType">The type of SQL statement to execute. </param>
		/// <param name="tableMapping">The <see cref="T:System.Data.Common.DataTableMapping" /> to send through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />. </param>
		// Token: 0x06000A96 RID: 2710 RVA: 0x00031378 File Offset: 0x0002F578
		public RowUpdatingEventArgs(DataRow dataRow, IDbCommand command, StatementType statementType, DataTableMapping tableMapping)
		{
			this.dataRow = dataRow;
			this.command = command;
			this.statementType = statementType;
			this.tableMapping = tableMapping;
			this.status = UpdateStatus.Continue;
			this.errors = null;
		}

		/// <summary>Gets the <see cref="T:System.Data.IDbCommand" /> to execute during the <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" /> operation.</summary>
		/// <returns>The <see cref="T:System.Data.IDbCommand" /> to execute during the <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x170001EC RID: 492
		// (get) Token: 0x06000A97 RID: 2711 RVA: 0x000313AC File Offset: 0x0002F5AC
		// (set) Token: 0x06000A98 RID: 2712 RVA: 0x000313B4 File Offset: 0x0002F5B4
		public IDbCommand Command
		{
			get
			{
				return this.command;
			}
			set
			{
				this.command = value;
			}
		}

		/// <summary>Gets any errors generated by the .NET Framework data provider when the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> executes.</summary>
		/// <returns>The errors generated by the .NET Framework data provider when the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> executes.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x170001ED RID: 493
		// (get) Token: 0x06000A99 RID: 2713 RVA: 0x000313C0 File Offset: 0x0002F5C0
		// (set) Token: 0x06000A9A RID: 2714 RVA: 0x000313C8 File Offset: 0x0002F5C8
		public Exception Errors
		{
			get
			{
				return this.errors;
			}
			set
			{
				this.errors = value;
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.DataRow" /> that will be sent to the server as part of an insert, update, or delete operation.</summary>
		/// <returns>The <see cref="T:System.Data.DataRow" /> to send through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x170001EE RID: 494
		// (get) Token: 0x06000A9B RID: 2715 RVA: 0x000313D4 File Offset: 0x0002F5D4
		public DataRow Row
		{
			get
			{
				return this.dataRow;
			}
		}

		/// <summary>Gets the type of SQL statement to execute.</summary>
		/// <returns>The type of SQL statement to execute.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x170001EF RID: 495
		// (get) Token: 0x06000A9C RID: 2716 RVA: 0x000313DC File Offset: 0x0002F5DC
		public StatementType StatementType
		{
			get
			{
				return this.statementType;
			}
		}

		/// <summary>Gets or sets the <see cref="T:System.Data.UpdateStatus" /> of the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> property.</summary>
		/// <returns>One of the <see cref="T:System.Data.UpdateStatus" /> values. The default is Continue.</returns>
		/// <filterpriority>1</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" PathDiscovery="*AllFiles*" />
		/// </PermissionSet>
		// Token: 0x170001F0 RID: 496
		// (get) Token: 0x06000A9D RID: 2717 RVA: 0x000313E4 File Offset: 0x0002F5E4
		// (set) Token: 0x06000A9E RID: 2718 RVA: 0x000313EC File Offset: 0x0002F5EC
		public UpdateStatus Status
		{
			get
			{
				return this.status;
			}
			set
			{
				this.status = value;
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.Common.DataTableMapping" /> to send through the <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</summary>
		/// <returns>The <see cref="T:System.Data.Common.DataTableMapping" /> to send through the <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x170001F1 RID: 497
		// (get) Token: 0x06000A9F RID: 2719 RVA: 0x000313F8 File Offset: 0x0002F5F8
		public DataTableMapping TableMapping
		{
			get
			{
				return this.tableMapping;
			}
		}

		/// <summary>Gets or sets the <see cref="T:System.Data.IDbCommand" /> object for an instance of this class.</summary>
		/// <returns>The <see cref="T:System.Data.IDbCommand" /> to execute during the <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />. </returns>
		// Token: 0x170001F2 RID: 498
		// (get) Token: 0x06000AA0 RID: 2720 RVA: 0x00031400 File Offset: 0x0002F600
		// (set) Token: 0x06000AA1 RID: 2721 RVA: 0x00031408 File Offset: 0x0002F608
		protected virtual IDbCommand BaseCommand
		{
			get
			{
				return this.command;
			}
			set
			{
				this.command = value;
			}
		}

		// Token: 0x040003AB RID: 939
		private DataRow dataRow;

		// Token: 0x040003AC RID: 940
		private IDbCommand command;

		// Token: 0x040003AD RID: 941
		private StatementType statementType;

		// Token: 0x040003AE RID: 942
		private DataTableMapping tableMapping;

		// Token: 0x040003AF RID: 943
		private UpdateStatus status;

		// Token: 0x040003B0 RID: 944
		private Exception errors;
	}
}
