using System;

namespace System.Data.Common
{
	/// <summary>Provides data for the RowUpdated event of a .NET Framework data provider.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x020000D9 RID: 217
	public class RowUpdatedEventArgs : EventArgs
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Data.Common.RowUpdatedEventArgs" /> class.</summary>
		/// <param name="dataRow">The <see cref="T:System.Data.DataRow" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />. </param>
		/// <param name="command">The <see cref="T:System.Data.IDbCommand" /> executed when <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" /> is called. </param>
		/// <param name="statementType">The type of SQL statement executed. </param>
		/// <param name="tableMapping">The <see cref="T:System.Data.Common.DataTableMapping" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />. </param>
		// Token: 0x06000A89 RID: 2697 RVA: 0x000312C8 File Offset: 0x0002F4C8
		public RowUpdatedEventArgs(DataRow dataRow, IDbCommand command, StatementType statementType, DataTableMapping tableMapping)
		{
			this.dataRow = dataRow;
			this.command = command;
			this.statementType = statementType;
			this.tableMapping = tableMapping;
			this.status = UpdateStatus.Continue;
		}

		/// <summary>Gets the <see cref="T:System.Data.IDbCommand" /> executed when <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" /> is called.</summary>
		/// <returns>The <see cref="T:System.Data.IDbCommand" /> executed when <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" /> is called.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x170001E4 RID: 484
		// (get) Token: 0x06000A8A RID: 2698 RVA: 0x00031300 File Offset: 0x0002F500
		public IDbCommand Command
		{
			get
			{
				return this.command;
			}
		}

		/// <summary>Gets any errors generated by the .NET Framework data provider when the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> was executed.</summary>
		/// <returns>The errors generated by the .NET Framework data provider when the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> was executed.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x170001E5 RID: 485
		// (get) Token: 0x06000A8B RID: 2699 RVA: 0x00031308 File Offset: 0x0002F508
		// (set) Token: 0x06000A8C RID: 2700 RVA: 0x0003132C File Offset: 0x0002F52C
		public Exception Errors
		{
			get
			{
				if (this.errors == null)
				{
					this.errors = new DataException("RowUpdatedEvent: No additional information is available!");
				}
				return this.errors;
			}
			set
			{
				this.errors = value;
			}
		}

		/// <summary>Gets the number of rows changed, inserted, or deleted by execution of the SQL statement.</summary>
		/// <returns>The number of rows changed, inserted, or deleted; 0 if no rows were affected or the statement failed; and -1 for SELECT statements.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170001E6 RID: 486
		// (get) Token: 0x06000A8D RID: 2701 RVA: 0x00031338 File Offset: 0x0002F538
		public int RecordsAffected
		{
			get
			{
				return this.recordsAffected;
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.DataRow" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</summary>
		/// <returns>The <see cref="T:System.Data.DataRow" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x170001E7 RID: 487
		// (get) Token: 0x06000A8E RID: 2702 RVA: 0x00031340 File Offset: 0x0002F540
		public DataRow Row
		{
			get
			{
				return this.dataRow;
			}
		}

		/// <summary>Gets the type of SQL statement executed.</summary>
		/// <returns>The type of SQL statement executed.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x170001E8 RID: 488
		// (get) Token: 0x06000A8F RID: 2703 RVA: 0x00031348 File Offset: 0x0002F548
		public StatementType StatementType
		{
			get
			{
				return this.statementType;
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.UpdateStatus" /> of the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> property.</summary>
		/// <returns>One of the <see cref="T:System.Data.UpdateStatus" /> values. The default is Continue.</returns>
		/// <filterpriority>1</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" PathDiscovery="*AllFiles*" />
		/// </PermissionSet>
		// Token: 0x170001E9 RID: 489
		// (get) Token: 0x06000A90 RID: 2704 RVA: 0x00031350 File Offset: 0x0002F550
		// (set) Token: 0x06000A91 RID: 2705 RVA: 0x00031358 File Offset: 0x0002F558
		public UpdateStatus Status
		{
			get
			{
				return this.status;
			}
			set
			{
				this.status = value;
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.Common.DataTableMapping" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</summary>
		/// <returns>The <see cref="T:System.Data.Common.DataTableMapping" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x170001EA RID: 490
		// (get) Token: 0x06000A92 RID: 2706 RVA: 0x00031364 File Offset: 0x0002F564
		public DataTableMapping TableMapping
		{
			get
			{
				return this.tableMapping;
			}
		}

		/// <summary>Gets the number of rows processed in a batch of updated records.</summary>
		/// <returns>int that specifies the number of row processed.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x170001EB RID: 491
		// (get) Token: 0x06000A93 RID: 2707 RVA: 0x0003136C File Offset: 0x0002F56C
		public int RowCount
		{
			get
			{
				return 0;
			}
		}

		/// <summary>Copies references to the modified rows into the provided array.</summary>
		/// <param name="array">The array of <see cref="T:System.Data.DataRow" /> to copy into.</param>
		/// <filterpriority>2</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" PathDiscovery="*AllFiles*" />
		/// </PermissionSet>
		// Token: 0x06000A94 RID: 2708 RVA: 0x00031370 File Offset: 0x0002F570
		public void CopyToRows(DataRow[] array)
		{
		}

		/// <summary>Copies references to the modified rows into the provided array. </summary>
		/// <param name="array">The array of <see cref="T:System.Data.DataRow" /> to copy into.</param>
		/// <param name="arrayIndex">The index in the array to start copying into.</param>
		/// <filterpriority>2</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" PathDiscovery="*AllFiles*" />
		/// </PermissionSet>
		// Token: 0x06000A95 RID: 2709 RVA: 0x00031374 File Offset: 0x0002F574
		public void CopyToRows(DataRow[] array, int arrayIndex)
		{
		}

		// Token: 0x040003A4 RID: 932
		private DataRow dataRow;

		// Token: 0x040003A5 RID: 933
		private IDbCommand command;

		// Token: 0x040003A6 RID: 934
		private StatementType statementType;

		// Token: 0x040003A7 RID: 935
		private DataTableMapping tableMapping;

		// Token: 0x040003A8 RID: 936
		private Exception errors;

		// Token: 0x040003A9 RID: 937
		private UpdateStatus status;

		// Token: 0x040003AA RID: 938
		private int recordsAffected;
	}
}
